---
apiVersion: v1
kind: Namespace
metadata:
  name: breizhsport
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend-breizhsport
  namespace: breizhsport
spec:
  serviceName: frontend-breizhsport
  replicas: 2
  selector:
    matchLabels:
      app: frontend-breizhsport
  template:
    metadata:
      labels:
        app: frontend-breizhsport
    spec:
      containers:
        - name: frontend
          image: rg.fr-par.scw.cloud/namespace-breizhsport/frontend-breizhsport
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-breizhsport
  namespace: breizhsport
spec:
  selector:
    app: frontend-breizhsport
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-breizhsport-ingress
  namespace: breizhsport
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  rules:
    - host: frontend.breizhsport.civit.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-breizhsport
                port:
                  number: 80
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: ms-backend-gateway-svc
                port:
                  number: 4000
  tls:
    - hosts:
        - frontend.breizhsport.civit.ovh
      secretName: frontend-breizhsport-tls
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-breizhsport-hpa
  namespace: breizhsport
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: frontend-breizhsport
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80